# Generated by Django 4.0.3 on 2022-08-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('des', models.TextField()),
                ('year', models.IntegerField(blank=True)),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
